#!/usr/bin/env bash
# NavPlayer — install Android build environment (WSL2 / Debian / Ubuntu)
# Usage:
#   chmod +x scripts/setup-android-env.sh
#   ./scripts/setup-android-env.sh          # SDK + build debug APK
#   ./scripts/setup-android-env.sh --emulator   # also install emulator (large download)
#   ./scripts/setup-android-env.sh --run        # build + launch emulator if installed

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SDK_ROOT="${ANDROID_SDK_ROOT:-$HOME/Android/Sdk}"
CMDLINE_VERSION="11076708"
JAVA_PKG="openjdk-17-jdk"
INSTALL_EMULATOR=false
RUN_AFTER=false

log() { printf '==> %s\n' "$*"; }
die() { printf '!! %s\n' "$*" >&2; exit 1; }

case "$(uname -m)" in
  x86_64|amd64)
    EMULATOR_ABI="x86_64"
    EMULATOR_IMAGE="system-images;android-34;google_apis;x86_64"
    ;;
  aarch64|arm64)
    EMULATOR_ABI="arm64-v8a"
    EMULATOR_IMAGE="system-images;android-34;google_apis;arm64-v8a"
    ;;
  *)
    die "Unsupported CPU for Android emulator: $(uname -m)"
    ;;
esac

for arg in "$@"; do
  case "$arg" in
    --emulator) INSTALL_EMULATOR=true ;;
    --run) RUN_AFTER=true; INSTALL_EMULATOR=true ;;
    -h|--help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (try --help)"
      exit 1
      ;;
  esac
done

# --- OS packages (sudo) ---
if ! command -v java >/dev/null 2>&1 || ! java -version 2>&1 | grep -q 'version "17'; then
  log "Installing $JAVA_PKG (requires sudo)..."
  sudo apt-get update -qq
  sudo apt-get install -y "$JAVA_PKG" wget unzip curl ca-certificates
else
  log "Java 17 already available"
  for pkg in wget unzip curl ca-certificates; do
    dpkg -s "$pkg" >/dev/null 2>&1 || {
      log "Installing $pkg..."
      sudo apt-get install -y "$pkg"
    }
  done
fi

export JAVA_HOME="$(dirname "$(dirname "$(readlink -f "$(command -v java)")")")"
export PATH="$JAVA_HOME/bin:$PATH"
log "JAVA_HOME=$JAVA_HOME"

# --- Android SDK command-line tools ---
mkdir -p "$SDK_ROOT/cmdline-tools"
TOOLS_ZIP="$SDK_ROOT/cmdline-tools/commandlinetools-linux.zip"
TOOLS_DIR="$SDK_ROOT/cmdline-tools/latest"

if [[ ! -x "$TOOLS_DIR/bin/sdkmanager" ]]; then
  log "Downloading Android command-line tools..."
  curl -fsSL \
    "https://dl.google.com/android/repository/commandlinetools-linux-${CMDLINE_VERSION}_latest.zip" \
    -o "$TOOLS_ZIP"
  rm -rf "$SDK_ROOT/cmdline-tools/latest" "$SDK_ROOT/cmdline-tools/cmdline-tools"
  unzip -q "$TOOLS_ZIP" -d "$SDK_ROOT/cmdline-tools"
  mv "$SDK_ROOT/cmdline-tools/cmdline-tools" "$TOOLS_DIR"
  rm -f "$TOOLS_ZIP"
else
  log "Command-line tools already present"
fi

export ANDROID_SDK_ROOT="$SDK_ROOT"
export ANDROID_HOME="$SDK_ROOT"
export PATH="$TOOLS_DIR/bin:$SDK_ROOT/platform-tools:$PATH"
EMULATOR_PATH="$SDK_ROOT/emulator"

# --- SDK components ---
log "Installing SDK packages (accepting licenses)..."
set +o pipefail
yes | sdkmanager --sdk_root="$SDK_ROOT" --licenses >/dev/null || true
set -o pipefail
sdkmanager --sdk_root="$SDK_ROOT" \
  "platform-tools" \
  "platforms;android-35" \
  "build-tools;35.0.0"

if $INSTALL_EMULATOR; then
  log "Installing emulator runtime libraries (requires sudo)..."
  sudo apt-get install -y libpulse0
  if [[ ! -r /dev/kvm ]] && ! getent group kvm | grep -qE ":($USER)$|:($USER),|,($USER)$|,($USER),"; then
    log "Granting KVM access for emulator (requires sudo)..."
    sudo gpasswd -a "$USER" kvm
  fi
  log "Installing emulator + system image ($EMULATOR_ABI, large download)..."
  sdkmanager --sdk_root="$SDK_ROOT" "emulator" "$EMULATOR_IMAGE"
  export PATH="$EMULATOR_PATH:$PATH"
fi

# --- Shell profile snippet ---
PROFILE="$HOME/.navplayer-android-env.sh"
cat >"$PROFILE" <<EOF
# NavPlayer Android build environment (generated by setup-android-env.sh)
export ANDROID_SDK_ROOT="$SDK_ROOT"
export ANDROID_HOME="$SDK_ROOT"
export JAVA_HOME="$JAVA_HOME"
export PATH="$TOOLS_DIR/bin:$SDK_ROOT/platform-tools:$SDK_ROOT/emulator:\$JAVA_HOME/bin:\$PATH"
EOF

grep -q 'navplayer-android-env.sh' "$HOME/.bashrc" 2>/dev/null || {
  echo '[ -f "$HOME/.navplayer-android-env.sh" ] && . "$HOME/.navplayer-android-env.sh"' >>"$HOME/.bashrc"
}

# --- Project local.properties ---
log "Writing $ROOT/local.properties"
printf 'sdk.dir=%s\n' "$SDK_ROOT" >"$ROOT/local.properties"

# --- Gradle wrapper ---
cd "$ROOT"
if [[ ! -x ./gradlew ]]; then
  if command -v gradle >/dev/null 2>&1; then
    log "Generating Gradle wrapper via system gradle..."
    gradle wrapper --gradle-version 8.9
  else
    log "Bootstrapping Gradle 8.9 wrapper..."
    GRADLE_ZIP="/tmp/gradle-8.9-bin.zip"
    curl -fsSL "https://services.gradle.org/distributions/gradle-8.9-bin.zip" -o "$GRADLE_ZIP"
    rm -rf /tmp/gradle-8.9
    unzip -q "$GRADLE_ZIP" -d /tmp
    (cd "$ROOT" && /tmp/gradle-8.9/bin/gradle wrapper --gradle-version 8.9)
    rm -rf /tmp/gradle-8.9 "$GRADLE_ZIP"
  fi
fi

# --- Build ---
log "Building debug APK..."
./gradlew :app:assembleDebug --no-daemon

APK="$ROOT/app/build/outputs/apk/debug/app-debug.apk"
if [[ -f "$APK" ]]; then
  log "APK ready: $APK"
  ls -lh "$APK"
else
  die "Build finished but APK not found at $APK"
fi

# --- Optional emulator run ---
if $RUN_AFTER; then
  export PATH="$EMULATOR_PATH:$PATH"
  command -v emulator >/dev/null || die "emulator not found — run with --emulator first"
  AVD_NAME="navplayer_land"
  if ! avdmanager list avd 2>/dev/null | grep -q "Name: $AVD_NAME"; then
    log "Creating landscape emulator AVD: $AVD_NAME"
    echo no | avdmanager create avd \
      -n "$AVD_NAME" \
      -k "$EMULATOR_IMAGE" \
      -d "pixel_5" \
      -b "$EMULATOR_ABI"
  fi
  log "Starting emulator (wait for boot, then install + launch app)..."
  : >/tmp/navplayer-emulator.log
  if [[ -r /dev/kvm ]]; then
    nohup emulator -avd "$AVD_NAME" -no-snapshot -gpu swiftshader_indirect >/tmp/navplayer-emulator.log 2>&1 &
  elif getent group kvm | grep -qE ":($USER)$|:($USER),|,($USER)$|,($USER),"; then
    nohup sg kvm -c "emulator -avd $AVD_NAME -no-snapshot -gpu swiftshader_indirect" >/tmp/navplayer-emulator.log 2>&1 &
  else
    die "KVM required. Run: sudo gpasswd -a $USER kvm"
  fi
  EMU_PID=$!
  sleep 5
  if ! kill -0 "$EMU_PID" 2>/dev/null; then
    printf '\n!! Emulator exited immediately. Last log lines:\n' >&2
    tail -20 /tmp/navplayer-emulator.log >&2 || true
    die "Emulator failed to start (see /tmp/navplayer-emulator.log; often libpulse0 or KVM: sudo gpasswd -a $USER kvm)"
  fi
  if ! timeout 180 adb wait-for-device; then
    tail -20 /tmp/navplayer-emulator.log >&2 || true
    die "Timed out waiting for emulator (see /tmp/navplayer-emulator.log)"
  fi
  for _ in $(seq 1 90); do
    [[ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" == "1" ]] && break
    sleep 2
  done
  adb shell settings put system user_rotation 1 || true
  adb install -r "$APK"
  adb shell am start -n com.dean.navplayer/.ui.MainActivity
  log "App launched on emulator (landscape)."
  log "Navidrome on this PC: use https://10.0.2.2:4533 in app Settings (not localhost)."
  log "Emulator log: /tmp/navplayer-emulator.log"
fi

cat <<EOF

Done.

Next steps:
  1. Reload shell:  source ~/.bashrc
  2. Install APK on head unit:  adb install -r "$APK"
     (USB debugging, or: adb connect HEADUNIT_IP:5555)
  3. In app Settings:  https://YOUR-NAVIDROME-HOST:4533  + user/password

Rebuild anytime:
  cd "$ROOT" && ./gradlew :app:assembleDebug

Release APK (smaller):
  cd "$ROOT" && ./gradlew :app:assembleRelease

Emulator (try locally before head unit):
  ./scripts/run-local.sh

Or:
  ./scripts/setup-android-env.sh --emulator --run

EOF
